postgres:
  username: habits_control
  password: root
  host: localhost
  port: 5444
  database: habits_control

server:
  address: 0.0.0.0:8082

jwt:
  token_seconds_ttl: 86400
  secret_key: abcdefgh123
